### ISSUE TITLE
Problem clearing cache in prod-environment

### ISSUE THREAD

**Issue by skilltryck** [Netpositive/NetpositiveDiscriminatorMapBundle#3]
I have installed this plugin but have a little problem.
Clearing cache (symfony2) in prod-environment raises a Doctrine MappingException.
Only way around is to manually delete cache and access prod-environment with debug-mode.

Is this a bug or am I doing anything wrong?

**Comment by fabianoroberto** [comment]
Someone have a solution for this bug?

**Comment by burci** [comment]
Sorry we did not have time to investigate, and we still use it with Symfony 2.0.

The problem is around cache warm up + entity annotation, this is why only the secound cache:warmup runs without error.

**Comment by fabianoroberto** [comment]
Yep, intact if i run 

```bash
app/console cache:clear --env=prod --no-warmup
```

i'm able to clear cache without any error

**Comment by fabianoroberto** [comment]
I found the issue with production enviroment: the Event loadClassMetadata was never fired in prod. To fix this problem I just add in the service the tag:

```xml
<tag name="doctrine.event_listener" event="loadClassMetadata"/>
```

I created a pull request about this

**Comment by burci** [comment]
@fabianoroberto thx for fixing it!

**Comment by fabianoroberto** [comment]
You are welcome
